version: 3

services:
  app:
    source:
      repo: MiltonAlbanez/Agente-Post-Automatico-Instagram
    build:
      builder: NIXPACKS
    deploy:
      startCommand: "python src/main.py multirun --limit 1"
      numReplicas: 1
      sleepApplication: false
      restartPolicyType: ON_FAILURE
      restartPolicyMaxRetries: 3

cron:
  morning_preseed:
    schedule: "55 8 * * *"
    command: "python src/main.py preseed"
    
  morning_post:
    schedule: "0 9 * * *"
    command: "python src/main.py autopost --no-replicate --style \"street, candid, natural light\""
    
  midday_preseed:
    schedule: "55 14 * * *"
    command: "python src/main.py preseed"
    
  midday_post:
    schedule: "0 15 * * *"
    command: "python src/main.py autopost --no-replicate --style \"portrait, studio-like natural light\""
    
  evening_preseed:
    schedule: "55 21 * * *"
    command: "python src/main.py preseed"
    
  evening_post:
    schedule: "0 22 * * *"
    command: "python src/main.py autopost --no-replicate --style \"evening golden hour, city scenes\""