version: 3

services:
  app:
    source:
      repo: MiltonAlbanez/Agente-Post-Automatico-Instagram
    build:
      builder: NIXPACKS
    deploy:
      sleepApplication: true

# NOTA: Railway NÃO lê configurações de cron do railway.yaml
# Os cron jobs devem ser configurados na interface web do Railway
# Consulte INSTRUCOES_RAILWAY_CRON.md para instruções detalhadas