version: 3

services:
  app:
    source:
      repo: MiltonAlbanez/Agente-Post-Automatico-Instagram
    build:
      builder: NIXPACKS
    deploy:
      numReplicas: 1
      sleepApplication: false
      restartPolicyType: ON_FAILURE
      restartPolicyMaxRetries: 10

cron:
  - name: preseed-06h-brt
    schedule: "0 9 * * *"
    command: "python src/main.py preseed"
    
  - name: autopost-06h-brt
    schedule: "5 9 * * *"
    command: "python src/main.py autopost --no-replicate --style 'Paisagem natural com animais fofos'"
    
  - name: preseed-12h-brt
    schedule: "0 15 * * *"
    command: "python src/main.py preseed"
    
  - name: autopost-12h-brt
    schedule: "5 15 * * *"
    command: "python src/main.py autopost --no-replicate --style 'Paisagem natural com animais fofos'"
    
  - name: preseed-19h-brt
    schedule: "0 22 * * *"
    command: "python src/main.py preseed"
    
  - name: autopost-19h-brt
    schedule: "5 22 * * *"
    command: "python src/main.py autopost --no-replicate --style 'Paisagem natural com animais fofos'"